version: 2

mkdocs:
  configuration: mkdocs.yml

build:
  os: 'ubuntu-22.04'
  tools:
    python: '3.11'

  jobs:
    post_create_environment:
      - pip install poetry
      - poetry install --only doc
      - poetry config virtualenvs.create false

    # pre_create_environment:
    #   - poetry install --only doc
# Config validation error in build.jobs. Expected one of (
# pre_checkout, post_checkout, pre_system_dependencies, post_system_dependencies, pre_create_environment,
# post_create_environment, pre_install, post_install, pre_build, post_build), got type str (steps).
# Double check the type of the value. A string may be required (e.g. "3.10" instead of 3.10)
