site_name: DTMASTER-INGEST-DOUGLASLEAL
repo_url: https://github.com/lealdouglas/dtmaster-ingest-douglasleal
repo_name: lealdouglas/dtmaster-ingest-douglasleal
edit_uri: tree/main/docs

theme:
  name: readthedocs
  logo: assets/sabre.png
  favicon: assets/sabre.png

markdown_extensions:
  - attr_list

extra_css:
  - stylesheets/extra.css

plugins:
- mkdocstrings:
  handlers:
    python:
      paths: [dtmaster_ingest_douglasleal]

      # - admonition
      # - pymdownx.tasklist
      # - pymdownx.superfences:
      #     custom_fences:
      #       - name: mermaid
      #         class: mermaid
      #         format: !!python/name:pymdownx.superfences.fence_code_format
      # - pymdownx.emoji:
      #     emoji_index: !!python/name:materialx.emoji.twemoji
      #     emoji_generator: !!python/name:materialx.emoji.to_svg
# theme:
#   name: material
#   language: pt-BR
#   logo: assets/logo.png
#   favicon: assets/logo.png

# markdown_extensions:
#   - attr_list
#   - admonition
#   - pymdownx.tasklist
#   - pymdownx.superfences:
#       custom_fences:
#         - name: mermaid
#           class: mermaid
#           format: !!python/name:pymdownx.superfences.fence_code_format
#   - pymdownx.emoji:
#       emoji_index: !!python/name:materialx.emoji.twemoji
#       emoji_generator: !!python/name:materialx.emoji.to_svg

# watch:
#    - notas_musicais

# extra:
#   commands:
#     run: notas-musicais
