name: Upload Python Package

on:
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Python
        uses: actions/setup-python@v4
        # see details (matrix, python-version, python-version-file, etc.)
        # https://github.com/actions/setup-python
      - name: Install poetry
        uses: abatilo/actions-poetry@v2
      - name: Setup a local virtual environment
        run: |
          poetry config virtualenvs.create false
      - name: Install the project dependencies
        run: poetry install
      - name: poetry lock --no-update
        run: poetry lock --no-update
      - name: publish
        run: poetry publish -u __token__ -p ${{ secrets.DTMASTER_INGEST }}
