name: Upload Python Package

on:
  workflow_dispatch:

jobs:
    python-build-n-publish:
        name: Build and publish Python distribution
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@main

            - name: Initialize Python 3.9
              uses: actions/setup-python@v3
              with:
                python-version: 3.9

            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install flake8
         
            - name: Lint with flake8
              run: |
                # stop the build if there are Python syntax errors or undefined names
                flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
                # exit-zero treats all errors as warnings.
                flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
          
            - name: Build binary wheel and a source tarball
              run: python setup.py sdist

            - name: Publish distribution to PyPI
              uses: pypa/gh-action-pypi-publish@master
              with:
                password: "pypi-AgEIcHlwaS5vcmcCJGVmMzMxNmM0LTE1NDgtNGEzMi04YTQ3LTNhNWNhMDYyYWE5MgACKlszLCJmNjIyM2I4Zi04ZjFjLTQzY2MtODRkNi00NGM5MGJiMzI5ZGQiXQAABiCEThhQhFEbyGAITkfie9mJjWEsUBZKNGQeLjEaqzq6xg"
                repository_url: https://upload.pypi.org/legacy/
